name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CONFIG_PATH: /home/runner/work/go-micro-tpl/go-micro-tpl/config.example.yaml
jobs:

  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Start  Kafka
      run: docker-compose up -d

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Install Windows packages
      if: runner.os == 'Windows'
      run: |
        choco install make -y
        dir env:

    - name: Build
      run: make build

    - name: Test
      run: make test && make coverage

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage.out