name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CONFIG_PATH: /home/runner/work/go-micro-tpl/go-micro-tpl/config.example.yaml
jobs:

  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    # - name: Set up MinGW
    #   if: runner.os == 'Windows'
    #   run: echo "C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH 
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Install Windows packages
      if: runner.os == 'Windows'
      run: |
        choco install make -y
        echo "CONFIG_PATH=$env:GITHUB_WORKSPACE\config.example.yaml" >> $env:GITHUB_ENV

    - name: Start Kafka  on Linux
      if: runner.os != 'Windows'
      run: docker-compose up -d
    - name: Start  Kafka and redis on Windows
      if: runner.os == 'Windows'
      run: |
        scripts/kafka_redis_install.ps1

    - name: Build
      run: make build
    - name: Check Kafka on Windows
      if: runner.os == 'Windows'
      run: netstat -ano | findstr 9092
    - name: Test
      run: |
        echo $CONFIG_PATH
        make test && make coverage

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage.out