name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CONFIG_PATH: /home/runner/work/go-micro-tpl/go-micro-tpl/config.example.yaml
  KAFKA_VERSION: 3.2.1
jobs:

  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up MinGW
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Install Windows packages
      if: runner.os == 'Windows'
      run: |
        choco install make -y
        echo $env:PATH
    - name: Start  Kafka on Linux
      if: runner.os != 'Windows'
      run: docker-compose up -d
    - name: Start  Kafka on Windows
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -uri https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_2.12-${KAFKA_VERSION}.tgz -outfile kafka.tgz
        7z.exe x .\kafka.tgz
        7z.exe x .\kafka.tar
        $base="kafka_2.12-${KAFKA_VERSION}"
        Start-Process -NoNewWindow $base\bin\windows\zookeeper-server-start.bat $base\config\zookeeper.properties
        Start-Sleep -Seconds 7
        Start-Process -NoNewWindow $base\bin\windows\kafka-server-start.bat $base\config\server.properties

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17


    - name: Build
      run: make build

    - name: Test
      run: make test && make coverage

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage.out